In [1]:
import pandas as pd
import numpy as np
import nltk
import seaborn as sns
from matplotlib import pyplot as plt
import plotly.express as px


In [2]:
reviews_df = pd.read_csv("D:/ML_2022/ML_workspace_2022/NLP/NLP_data/rotten_tomatoes_critic_reviews.csv")
print(reviews_df.shape)
reviews_df.head(5)

(1130017, 8)


rotten_tomatoes_link      critic_name  top_critic           publisher_name  \
0            m/0814255  Andrew L. Urban       False           Urban Cinefile   
1            m/0814255    Louise Keller       False           Urban Cinefile   
2            m/0814255              NaN       False      FILMINK (Australia)   
3            m/0814255     Ben McEachen       False  Sunday Mail (Australia)   
4            m/0814255      Ethan Alter        True       Hollywood Reporter   

  review_type review_score review_date  \
0       Fresh          NaN  2010-02-06   
1       Fresh          NaN  2010-02-06   
2       Fresh          NaN  2010-02-09   
3       Fresh        3.5/5  2010-02-09   
4      Rotten          NaN  2010-02-10   

                                      review_content  
0  A fantasy adventure that fuses Greek mythology...  
1  Uma Thurman as Medusa, the gorgon with a coiff...  
2  With a top-notch cast and dazzling special eff...  
3  Whether audiences will get behind The Lightnin...  
4  What's really lacking in The Lightning Thief i...

In [4]:
reviews_df.isna().sum()

rotten_tomatoes_link         0
critic_name              18529
top_critic                   0
publisher_name               0
review_type                  0
review_score            305936
review_date                  0
review_content           65806
dtype: int64

In [22]:
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re

In [18]:
stemmer = PorterStemmer()
lem = WordNetLemmatizer()

word_list = ["historical","finally","suspectful","going","making","developing","goes"]
for word in word_list:
    print("Stemmer:",stemmer.stem(word))
    print("lemmatiser:",lem.lemmatize(word))
    print("--------------------------")

Stemmer: histor
lemmatiser: historical
--------------------------
Stemmer: final
lemmatiser: finally
--------------------------
Stemmer: suspect
lemmatiser: suspectful
--------------------------
Stemmer: go
lemmatiser: going
--------------------------
Stemmer: make
lemmatiser: making
--------------------------
Stemmer: develop
lemmatiser: developing
--------------------------
Stemmer: goe
lemmatiser: go
--------------------------


In [19]:
para ="Reuniting in the present, the Avengers place the Stones into a gauntlet that Stark, Banner, and Rocket had built. Having the most resistance to their radiation, Banner wields the gauntlet and reverses Thanos's disintegrations. Meanwhile, 2014-Nebula, impersonating her future self, uses the time machine to transport 2014-Thanos and his warship to the present, which he then uses to destroy the Avengers Compound. Present-day Nebula convinces 2014-Gamora to betray Thanos, but is unable to convince 2014-Nebula and kills her. Thanos overpowers Stark, Thor, and a Mjolnir-wielding Rogers and summons his army to retrieve the Stones, intent on using them to destroy the universe and create a new one. A restored Stephen Strange arrives with other sorcerers, the restored Avengers and Guardians of the Galaxy, the Ravagers, and the armies of Wakanda and Asgard to fight Thanos's army. Danvers also arrives and destroys Thanos's warship, but Thanos overpowers her and seizes the gauntlet. Stark steals the Stones and uses them to disintegrate Thanos and his army, at the cost of his life."
print(para)

Reuniting in the present, the Avengers place the Stones into a gauntlet that Stark, Banner, and Rocket had built. Having the most resistance to their radiation, Banner wields the gauntlet and reverses Thanos's disintegrations. Meanwhile, 2014-Nebula, impersonating her future self, uses the time machine to transport 2014-Thanos and his warship to the present, which he then uses to destroy the Avengers Compound. Present-day Nebula convinces 2014-Gamora to betray Thanos, but is unable to convince 2014-Nebula and kills her. Thanos overpowers Stark, Thor, and a Mjolnir-wielding Rogers and summons his army to retrieve the Stones, intent on using them to destroy the universe and create a new one. A restored Stephen Strange arrives with other sorcerers, the restored Avengers and Guardians of the Galaxy, the Ravagers, and the armies of Wakanda and Asgard to fight Thanos's army. Danvers also arrives and destroys Thanos's warship, but Thanos overpowers her and seizes the gauntlet. Stark steals th

In [20]:
# tokenisation- sentence tokeniser splits the paragraphs into list of sentences
nltk.download('punkt')
sentences = nltk.sent_tokenize(para)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\MAYANK\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [21]:
sentences

['Reuniting in the present, the Avengers place the Stones into a gauntlet that Stark, Banner, and Rocket had built.',
 "Having the most resistance to their radiation, Banner wields the gauntlet and reverses Thanos's disintegrations.",
 'Meanwhile, 2014-Nebula, impersonating her future self, uses the time machine to transport 2014-Thanos and his warship to the present, which he then uses to destroy the Avengers Compound.',
 'Present-day Nebula convinces 2014-Gamora to betray Thanos, but is unable to convince 2014-Nebula and kills her.',
 'Thanos overpowers Stark, Thor, and a Mjolnir-wielding Rogers and summons his army to retrieve the Stones, intent on using them to destroy the universe and create a new one.',
 "A restored Stephen Strange arrives with other sorcerers, the restored Avengers and Guardians of the Galaxy, the Ravagers, and the armies of Wakanda and Asgard to fight Thanos's army.",
 "Danvers also arrives and destroys Thanos's warship, but Thanos overpowers her and seizes the

In [25]:
def text_clean(sent):
    review = re.sub('[^a-zA-Z]',' ',sent)
    review =review.lower()
    return review


In [28]:
corpus=[]
for sent in sentences:
    cleaned_sent = text_clean(sent)
    print(cleaned_sent)
    print("----------")
    corpus.append(cleaned_sent)

reuniting in the present  the avengers place the stones into a gauntlet that stark  banner  and rocket had built 
----------
having the most resistance to their radiation  banner wields the gauntlet and reverses thanos s disintegrations 
----------
meanwhile       nebula  impersonating her future self  uses the time machine to transport      thanos and his warship to the present  which he then uses to destroy the avengers compound 
----------
present day nebula convinces      gamora to betray thanos  but is unable to convince      nebula and kills her 
----------
thanos overpowers stark  thor  and a mjolnir wielding rogers and summons his army to retrieve the stones  intent on using them to destroy the universe and create a new one 
----------
a restored stephen strange arrives with other sorcerers  the restored avengers and guardians of the galaxy  the ravagers  and the armies of wakanda and asgard to fight thanos s army 
----------
danvers also arrives and destroys thanos s warship  

In [29]:
corpus

['reuniting in the present  the avengers place the stones into a gauntlet that stark  banner  and rocket had built ',
 'having the most resistance to their radiation  banner wields the gauntlet and reverses thanos s disintegrations ',
 'meanwhile       nebula  impersonating her future self  uses the time machine to transport      thanos and his warship to the present  which he then uses to destroy the avengers compound ',
 'present day nebula convinces      gamora to betray thanos  but is unable to convince      nebula and kills her ',
 'thanos overpowers stark  thor  and a mjolnir wielding rogers and summons his army to retrieve the stones  intent on using them to destroy the universe and create a new one ',
 'a restored stephen strange arrives with other sorcerers  the restored avengers and guardians of the galaxy  the ravagers  and the armies of wakanda and asgard to fight thanos s army ',
 'danvers also arrives and destroys thanos s warship  but thanos overpowers her and seizes the

In [33]:
from nltk.tokenize import word_tokenize
# defining stop words
stop_en = set(stopwords.words('english'))


In [52]:
from nltk.tokenize.treebank import TreebankWordDetokenizer

test_corpus = []
def nlp_text_clean_pipeline(text):
    
    text=re.sub('[^a-zA-Z]', " ", str(text))
    text=text.lower()
    
    word_tokens = word_tokenize(text)
    print("words tokensised:\n",word_tokens)
    filtered_words = [w for w in word_tokens if not w in stop_en]
    print("after removing stop_words:\n",filtered_words)

    # lemmatising filtered words
    lem_words = [lem.lemmatize(w) for w in filtered_words]
    print("after lemmatisation:\n",lem_words)


    reformed_clean_text = TreebankWordDetokenizer().detokenize(lem_words)
    print("reformed clean_text:\n",reformed_clean_text)
    test_corpus.append(reformed_clean_text)
    # return text

In [49]:
test_sent='Present-day Nebula convinces 2014-Gamora to betray Thanos, but is unable to convince 2014-Nebula and kills her.'
nlp_text_clean_pipeline(test_sent)

words tokensised:
 ['present', 'day', 'nebula', 'convinces', 'gamora', 'to', 'betray', 'thanos', 'but', 'is', 'unable', 'to', 'convince', 'nebula', 'and', 'kills', 'her']
after removing stop_words:
 ['present', 'day', 'nebula', 'convinces', 'gamora', 'betray', 'thanos', 'unable', 'convince', 'nebula', 'kills']
after lemmatisation:
 ['present', 'day', 'nebula', 'convinces', 'gamora', 'betray', 'thanos', 'unable', 'convince', 'nebula', 'kill']
reformed clean_text:
 present day nebula convinces gamora betray thanos unable convince nebula kill


In [64]:
test_corpus=[]
nlp_text_clean_pipeline(test_sent)

words tokensised:
 ['present', 'day', 'nebula', 'convinces', 'gamora', 'to', 'betray', 'thanos', 'but', 'is', 'unable', 'to', 'convince', 'nebula', 'and', 'kills', 'her']
after removing stop_words:
 ['present', 'day', 'nebula', 'convinces', 'gamora', 'betray', 'thanos', 'unable', 'convince', 'nebula', 'kills']
after lemmatisation:
 ['present', 'day', 'nebula', 'convinces', 'gamora', 'betray', 'thanos', 'unable', 'convince', 'nebula', 'kill']
reformed clean_text:
 present day nebula convinces gamora betray thanos unable convince nebula kill


In [65]:
print(test_corpus)

['present day nebula convinces gamora betray thanos unable convince nebula kill']


Now, that corpus consisting of cleaned text is built, we will build VOCABULARY which is esentially a mapping of each of the unique word and its index in vectorised form

BAG OF WORDS:

In [66]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [69]:
X = cv.fit_transform(test_corpus)

In [70]:
# Vacabulary consists of unique words and their index mapping in the vector representation
cv.vocabulary_

{'present': 7,
 'day': 3,
 'nebula': 6,
 'convinces': 2,
 'gamora': 4,
 'betray': 0,
 'thanos': 8,
 'unable': 9,
 'convince': 1,
 'kill': 5}

In [75]:
print("--------Actual corpus ---------------")
print(test_corpus)
print("----------------BOW representation of corpus ---------")
print(X.toarray())

--------Actual corpus ---------------
['present day nebula convinces gamora betray thanos unable convince nebula kill']
----------------BOW representation of corpus ---------
[[1 1 1 1 1 1 2 1 1 1]]


Notice that BOW doesn't give actual binary 1 and 0 vector representation unless flag binary=TRUE is set. So, to get binary vector rep, set the flag TRue during intialisation of CountVectoriser()

cv=CountVectorizer(binary=True)

If you want to include n-grams into Count Vectoriser. use flag ngram_range=(1,3) , 1,3 implies that unigram, bigram, trigrams are included in the vectorisation

In [84]:
cv2 = CountVectorizer(binary=True,ngram_range=(1,3))
X2=cv2.fit_transform(test_corpus)
cv2.vocabulary_

{'present': 20,
 'day': 9,
 'nebula': 16,
 'convinces': 6,
 'gamora': 12,
 'betray': 0,
 'thanos': 23,
 'unable': 26,
 'convince': 3,
 'kill': 15,
 'present day': 21,
 'day nebula': 10,
 'nebula convinces': 17,
 'convinces gamora': 7,
 'gamora betray': 13,
 'betray thanos': 1,
 'thanos unable': 24,
 'unable convince': 27,
 'convince nebula': 4,
 'nebula kill': 19,
 'present day nebula': 22,
 'day nebula convinces': 11,
 'nebula convinces gamora': 18,
 'convinces gamora betray': 8,
 'gamora betray thanos': 14,
 'betray thanos unable': 2,
 'thanos unable convince': 25,
 'unable convince nebula': 28,
 'convince nebula kill': 5}

In [85]:
print("BOW with 1,2,3-grams included")
print(X2.toarray())

BOW with 1,2,3-grams included
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


TF-IDF:

In [86]:
from sklearn.feature_extraction.text import TfidfVectorizer

tidf = TfidfVectorizer()
X3=tidf.fit_transform(test_corpus)

print(tidf.vocabulary_)


{'present': 7, 'day': 3, 'nebula': 6, 'convinces': 2, 'gamora': 4, 'betray': 0, 'thanos': 8, 'unable': 9, 'convince': 1, 'kill': 5}


In [88]:

print("original corpus:\n",test_corpus)
print("------------BOW--------------------")
print(X.toarray())
print("-------------TF-IDF---------------------")
print(X3.toarray())

original corpus:
 ['present day nebula convinces gamora betray thanos unable convince nebula kill']
------------BOW--------------------
[[1 1 1 1 1 1 2 1 1 1]]
-------------TF-IDF---------------------
[[0.2773501 0.2773501 0.2773501 0.2773501 0.2773501 0.2773501 0.5547002
  0.2773501 0.2773501 0.2773501]]


In [63]:

for text in sentences:
    nlp_text_clean_pipeline(text)
    print("-----------")


words tokensised:
 ['reuniting', 'in', 'the', 'present', 'the', 'avengers', 'place', 'the', 'stones', 'into', 'a', 'gauntlet', 'that', 'stark', 'banner', 'and', 'rocket', 'had', 'built']
after removing stop_words:
 ['reuniting', 'present', 'avengers', 'place', 'stones', 'gauntlet', 'stark', 'banner', 'rocket', 'built']
after lemmatisation:
 ['reuniting', 'present', 'avenger', 'place', 'stone', 'gauntlet', 'stark', 'banner', 'rocket', 'built']
reformed clean_text:
 reuniting present avenger place stone gauntlet stark banner rocket built
-----------
words tokensised:
 ['having', 'the', 'most', 'resistance', 'to', 'their', 'radiation', 'banner', 'wields', 'the', 'gauntlet', 'and', 'reverses', 'thanos', 's', 'disintegrations']
after removing stop_words:
 ['resistance', 'radiation', 'banner', 'wields', 'gauntlet', 'reverses', 'thanos', 'disintegrations']
after lemmatisation:
 ['resistance', 'radiation', 'banner', 'wields', 'gauntlet', 'revers', 'thanos', 'disintegration']
reformed clean_tex